[package]
name = "rubycave-client"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
ouroboros = "0.18.4"
pollster = "0.3.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wgpu = "0.20.1"
winit = "0.30.3"
