[package]
name = "rubycave_mc_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"

[build-dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
serde_json = "1.0.122"
zip = "2.1.6"
