[package]
name = "rubycave"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = "0.19.6"
glam = { version = "0.28.0", features = ["debug-glam-assert", "bytemuck"] }

[build-dependencies]
capnpc = "0.19.0"
glob = "0.3.1"
